version: '3.5'

networks:
  custom_network:
    driver: bridge


services:
  postgres_main:
    container_name: postgres_main
    image: postgres:12.17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    networks:
      - custom_network
    volumes:
      - pdata:/var/lib/postgresql/data

  # zookeeper:
  #   container_name: zookeeper
  #   image: bitnami/zookeeper:3.9.1
  #   ports: 
  #     - "2181:2181"
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #   networks:
  #     - custom_network
  #   depends_on:
  #     - postgres_main
    
    
  kafka:
    container_name: kafka
    image: bitnami/kafka:3.6.1
    ports:
      - "9094:9094"
    environment:
    #  - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@localhost:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092, CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

    networks:
      - custom_network
    # depends_on:
    #   - zookeeper

volumes:
  pdata:
    external: true
    name:
      5a64e9dcd025fc9a173e592b047aac519e61536c7a88db553712872630eb2acf
