version: '3.5'

services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:12.17-alpine
    volumes:
      - pdata:/var/lib/postgresql/data

volumes:
  pdata:
    external: true
    name:
      5a64e9dcd025fc9a173e592b047aac519e61536c7a88db553712872630eb2acf
